### ISSUE TITLE
where can I find the thesis

### ISSUE THREAD

**Issue by GELIELEO** [rjbruin/causal-discovery-with-lstm#1]
I am intersting in causal inference and I found this nice work,hoping to learning deeper about it.

**Comment by rjbruin** [comment]
Thanks for your interest! You can download it here: [Bruintjes2017.pdf](https://github.com/rjbruin/causal-discovery-with-lstm/files/3124993/Bruintjes2017.pdf)

**Comment by GELIELEO** [comment]
Thank you very much!!!
